services:
  mysql:
    ports:
      - "3307:3306"

  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      # Expose 443 if you want but it won't work with this config without SSL
    depends_on:
      - web

  # Disable certbot in dev explicitly if needed, though profile handles it
