services:
  web:
    image: acxcoldblood/dnotes:${IMAGE_TAG}
    container_name: devops-flask
    restart: always
    env_file:
      - .env
    expose:
      - "5000"
    depends_on:
      mysql:
        condition: service_healthy
